# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MLB_Highlights.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 365)
        MainWindow.setMinimumSize(QtCore.QSize(914, 365))
        MainWindow.setMaximumSize(QtCore.QSize(914, 365))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Ken/Pictures/python Icons/MLB_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 70, 261, 291))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(10, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.get_game_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_game_button.setGeometry(QtCore.QRect(180, 30, 91, 31))
        self.get_game_button.setObjectName("get_game_button")
        self.free_game_label = QtWidgets.QLabel(self.centralwidget)
        self.free_game_label.setGeometry(QtCore.QRect(510, 30, 141, 21))
        self.free_game_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.free_game_label.setText("")
        self.free_game_label.setScaledContents(True)
        self.free_game_label.setAlignment(QtCore.Qt.AlignCenter)
        self.free_game_label.setObjectName("free_game_label")
        self.away_team_label = QtWidgets.QLabel(self.centralwidget)
        self.away_team_label.setGeometry(QtCore.QRect(430, 20, 71, 61))
        self.away_team_label.setText("")
        self.away_team_label.setScaledContents(True)
        self.away_team_label.setAlignment(QtCore.Qt.AlignCenter)
        self.away_team_label.setObjectName("away_team_label")
        self.home_team_label = QtWidgets.QLabel(self.centralwidget)
        self.home_team_label.setGeometry(QtCore.QRect(660, 20, 71, 61))
        self.home_team_label.setText("")
        self.home_team_label.setScaledContents(True)
        self.home_team_label.setAlignment(QtCore.Qt.AlignCenter)
        self.home_team_label.setObjectName("home_team_label")
        self.replay_window = QtWidgets.QListWidget(self.centralwidget)
        self.replay_window.setGeometry(QtCore.QRect(280, 90, 611, 271))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        self.replay_window.setFont(font)
        self.replay_window.setObjectName("replay_window")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 0, 231, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(290, 60, 121, 17))
        self.radioButton.setObjectName("radioButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MLB Replay"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "MMMM d yyyy"))
        self.label.setText(_translate("MainWindow", "Select date for replays"))
        self.get_game_button.setText(_translate("MainWindow", "Get Games"))
        self.label_2.setText(_translate("MainWindow", "MLB.TV Free Game of the Day"))
        self.radioButton.setText(_translate("MainWindow", "Play all replays"))

